name: Development Operations
on:
  push:
    branches:
      - devops
jobs:
  checkout:
    runs-on: CentOS Linux release 7.9.2009 (Core)
#    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4
      - run: ls -al
      - run: cat .github/workflows/main.yml
