# 이 워크플로우의 이름입니다. GitHub Actions에서 이 워크플로우를 식별하는 데 사용됩니다.
name: Run Python Code
# 워크플로우를 트리거하는 이벤트를 정의합니다.
on:
  # 리포지토리에 푸시가 발생했을 때 워크플로우가 실행됩니다.
  push:
    # devops 브랜치에 푸시될 때 워크플로우가 실행됩니다.
    branches:
      - devops

# 워크플로우에서 실행될 작업을 정의합니다.
jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run Python script
        run: python step/step_2557.py # 이곳에 실제 파이썬 파일명을 적어주세요.

  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: hello
        run: ls -al
        continue-on-error: true
      - name: Step 2
        id: world
        run: ls -al
        continue-on-error: true
      - name: Check on failures
        if: steps.hello.outcome != 'success' || steps.world.outcome != 'success'
        run: exit 1