name: Development Operations
on:
  push:
    branches:
      - devops
jobs:
  checkout:
    # github action 에서 Linux OS 는 ubuntu 만 사용
    # CentOS 의 경우에도 ubuntu 사용
    runs-on: ubuntu-22.04
#    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4
      - run: ls -al
      - run: cat .github/workflows/main.yml
